language: R
sudo: false
cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

matrix:
  include:
    - os: linux
      env: RVERSION=release
      r_github_packages:
        - jimhester/covr
      after_success:
        - travis_wait 20 Rscript -e 'covr::codecov()'
    - os: linux
      env: RVERSION=2.5.1
    - os: linux
      env: RVERSION=devel
    - os: osx
      env: RVERSION=release
      before_install:
        - curl -O http://kingaa.github.io/scripts/mac-fortran.sh
        - sh mac-fortran.sh
        - rm -f mac-fortran.sh
      after_failure: cat /Users/travis/build/kingaa/subplex/subplex.Rcheck/00install.out /Users/travis/build/kingaa/subplex/subplex.Rcheck/00check.log
    - os: osx
      env: RVERSION=devel
      before_install:
        - curl -O http://kingaa.github.io/scripts/mac-fortran.sh
        - sh mac-fortran.sh
        - rm -f mac-fortran.sh
